development:
  adapter: mysql
  database: library_development
  username: root
  password:
  host: localhost
test:
  adapter: mysql
  database: library_test
  username: root
  password: 
  host: localhost
production:
  adapter: mysql
  database: library_production
  username: root
  password: zEetzhxY1UmqIjmWBx6R
  host: mysql://root:zEetzhxY1UmqIjmWBx6R@thegame-georgeciobanu.dotcloud.com:23306
